[project]
name = "automated-car-simulation-over-generations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "neat-python>=1.1.0",
    "numpy>=2.4.1",
    "pygame>=2.6.1",
    "scipy>=1.17.0",
]
